= VSHN PDF Generator based on Asciidoctor

This project generates a Docker image to be used to generate PDF books with a standard VSHN style and fonts.

The image is available in https://hub.docker.com/r/vshn/asciidoctor-pdf[Docker Hub].

== Build

Run the `make` command to build the image.

== Usage

Run the following command to build a PDF using an Asciidoc file as a basis:

`docker run --rm --tty --user "$(id -u)" --volume "${PWD}":/documents vshn/asciidoctor-pdf:1.5.3 file.adoc`

Any parameters passed after the command line will be fed directly to Asciidoctor, for example

`docker run --rm --tty --user "$(id -u)" --volume "${PWD}":/documents vshn/asciidoctor-pdf:1.5.3 file.adoc --destination-dir=./_archive`

== Default Attributes

This project sets the following default attributes for the generation of the PDF:

* doctype=book
* pdf-themesdir=/theme
* pdf-theme=vshn
* pdf-fontsdir=/fonts
* pdf-page-size=A4
* mathematical-format=svg
* stem=latexmath
* hide-uri-scheme
* experimental
* source-highlighter=rouge
* pygments-style=abap
* icons=font
* icon-set=fi
* numbered
* toc
* toclevels=2
* sectnumlevels=2
* leveloffset=+1

These attributes can be overridden on the command line passing the corresponding `--attribute` or `-a` parameter.
