= VSHN PDF Generator based on Asciidoctor

This project generates a container image to be used to generate PDF books with a standard VSHN style and fonts.

== Build

Run the `make` command to build the image.

== Usage

Run the following command to build a PDF using an Asciidoc file as a basis:

`podman run --rm --volume "${PWD}":/documents ghcr.io/vshn/asciidoctor-pdf:1.39.1 file.adoc`

Any parameters passed after the command line will be fed directly to Asciidoctor, for example

`podman run --rm --volume "${PWD}":/documents ghcr.io/vshn/asciidoctor-pdf:1.39.1 file.adoc --destination-dir=./_archive`

== Default Attributes

This project sets the following default attributes for the generation of the PDF:

* doctype=book
* pdf-themesdir=/theme
* pdf-theme=vshn
* pdf-fontsdir=/fonts
* pdf-page-size=A4
* mathematical-format=svg
* stem=latexmath
* hide-uri-scheme
* experimental
* source-highlighter=rouge
* pygments-style=abap
* icons=font
* icon-set=fi
* numbered
* toc
* toclevels=2
* sectnumlevels=2
* leveloffset=+1

These attributes can be overridden on the command line passing the corresponding `--attribute` or `-a` parameter.

== Extensions

This container image includes these additional extensions:

- https://github.com/Alwinator/asciidoctor-lists[asciidoctor-lists]

