:author: VSHN AG
:revdate: {docdate}
:revnumber: 1.2
:email:  handbook@vshn.ch
:copyright: CC-BY-SA 3.0
:doctitle: VSHN Sample PDF Book
:producer: VSHN AG
:creator: VSHN AG
:description: Sample document to create complex PDFs with VSHN style
:keywords: VSHN, VSHNeer, work, systems, DevOps
:lang: en
:imagesdir: {docdir}/images


[colophon]
= Colophon

This is a sample book built with the `vshn/asciidoctor-pdf` docker image.


= First Part

[partintro]
--
This is the first part!
--



== Introduction

A simple http://asciidoc.org[AsciiDoc] document.

A ((paragraph)) followed by an unordered list{empty}footnote:[AsciiDoc supports unordered, ordered, and description lists.] with square bullets.footnote:[You may choose from square, disc, and circle for the bullet style.]

[square]
* item 1
* item 2

Here's how you say "`Hello, World!`" in ((Prawn)):

.Create a basic PDF document using Prawn
[source,ruby]
----
require 'prawn'

Prawn::Document.generate 'example.pdf' do
  text 'Hello, World!'
end
----

And here goes a diagram

[ditaa]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....



= Second Part

[partintro]
--
This is the second part!
--


== Conclusion

Inline equation: stem:[e^{ i \theta_1} = \cos{\theta_1} + i \sin{\theta_1}]

Block equation:

[stem]
++++
\frac{\partial^2 u}{\partial x^2}=\frac{1}{c^2} \frac{\partial^2 u}{\partial t^2}\]
++++

A UML diagram:

[plantuml, diagram-classes, png]     
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....

That's ((all)), folks!



[index]
= Index
